name: CI Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          bash bin/setup.sh 
      - name: Lint with pylint
        run: |
          pylint $(git ls-files '*.py') || true
      - name: Run unit tests with Nose
        run: nosetests --with-coverage
      - name: Run Flask app
        run: |
          export FLASK_APP=service/__init__.py
          flask run --host=0.0.0.0 &
          sleep 10
      - name: Run bdd tests
        run: |
          behave
