name: Setup TDD/BDD Final Project Environment

on:
  push:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      run: |
        echo "**************************************************"
        echo " Setting up TDD/BDD Final Project Environment"
        echo "**************************************************"

        echo "*** Installing Python 3.9 and Virtual Environment"
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y python3.9

        echo "*** Checking the Python version..."
        python3 --version

        echo "*** Creating a Python virtual environment"
        python3 -m venv ~/venv

        echo "*** Installing Selenium and Chrome for BDD"
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y sqlite3 ca-certificates chromium-driver python3-selenium

        echo "*** Installing Python depenencies..."
        source ~/venv/bin/activate && python3 -m pip install --upgrade pip wheel
        source ~/venv/bin/activate && pip install -r requirements.txt

        echo "*** Establishing .env file"
        cp dot-env-example .env

        echo "*** Starting the Postgres Docker container..."
        make db

        echo "*** Checking the Postgres Docker container..."
        docker ps

        echo "**************************************************"
        echo " TDD/BDD Final Project Environment Setup Complete"
    - name: Analysing the code with pylint
      run: |
        source ~/venv/bin/activate
        python3 -m pylint $(git ls-files '*.py') || true
    - name: Run unit tests
      run: |
        nosetests --with-coverage
    - name: Run Flask app
      run: |
        export FLASK_APP=service/__init__.py
        flask run --host=0.0.0.0 &
        sleep 10
    - name: Run bdd tests
      run: |
        python3 -m behave
