name: Setup TDD/BDD Final Project Environment

on:
  push:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        python-version: 3.9

    - name: Set up Enviroment
      run: |
        echo "*** Configuring the developer environment..."
        echo "# TDD/BDD Final Project additions" >> ~/.bashrc
        echo "export GITHUB_ACCOUNT=creepoff1" >> ~/.bashrc
        echo 'export PS1="\[\e]0;\u:\W\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u\[\033[00m\]:\[\033[01;34m\]\W\[\033[00m\]\$ "' >> ~/.bashrc
        echo "source ~/venv/bin/activate" >> ~/.bashrc

        echo "*** Installing Selenium and Chrome for BDD"
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y sqlite3 ca-certificates chromium-driver python3-selenium

        echo "*** Installing Python depenencies..."
        source ~/venv/bin/activate && python3 -m pip install --upgrade pip wheel
        source ~/venv/bin/activate && pip install -r requirements.txt

        echo "*** Establishing .env file"
        cp dot-env-example .env

        echo "*** Starting the Postgres Docker container..."
        make db

        echo "*** Checking the Postgres Docker container..."
        docker ps

        echo "**************************************************"
        echo " TDD/BDD Final Project Environment Setup Complete"
        echo ""
        echo "Use 'exit' to close this terminal and open a new one to initialize the environment"
        echo ""
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') || true
    - name: Run unit tests
      run: |
        nosetests --with-coverage
    - name: Run Flask app
      run: |
        export FLASK_APP=service/__init__.py
        flask run --host=0.0.0.0 &
        sleep 10
    - name: Run bdd tests
      run: |
        behave
